project:
  type: book
  output-dir: docs

book:
  title: "PF0914 Desarrollo de sistemas de información geográfica en la Web 2024-I"
  author: "Manuel Vargas"
  date: "2024-03-17"
  chapters:
    - index.qmd
    - programa-curso.qmd
    - part: parte-i-lenguajes-basicos-desarrollo-sig-web.qmd
      chapters:
        - 01-introduccion-desarrollo-sig-web.qmd    
        - 02-html.qmd

bibliography: referencias.bib

format:
  html:
    lang: es
    theme: cosmo