project:
  type: book
  output-dir: docs

book:
  title: "PF0914 Desarrollo de sistemas de información geográfica en la Web 2024-I"
  author: "Manuel Vargas"
  date: "2024-03-17"
  chapters:
    - index.qmd
    - programa-curso.qmd
    - part: parte-i-lenguajes-basicos-desarrollo-sig-web.qmd
      chapters:
        - 01-introduccion-desarrollo-sig-web.qmd    
        - 02-html.qmd
        - 03-css.qmd
        - 04-js.qmd
    - part: parte-ii-leaflet.qmd
      chapters:
        - 05-leaflet.qmd            
    - part: parte-iv-evaluaciones.qmd
      chapters: 
        - tarea-01.qmd        

bibliography: referencias.bib

format:
  html:
    lang: es
    theme: cosmo
    toc-depth: 4    
    toc-expand: true